import { Item } from '../types';

export const mockData: Item[] = [
  // ============================================
  // LEVEL 1: Root Folders
  // ============================================
  {
    id: '1001',
    name: 'Clinical Services',
    type: 'folder',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 15, 2025',
    lastUpdatedBy: 'Dr. Sarah Johnson',
    parentId: null,
    children: [],
  },
  {
    id: '1002',
    name: 'Patient Care Resources',
    type: 'folder',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 14, 2025',
    lastUpdatedBy: 'Dr. Sarah Johnson',
    parentId: null,
    children: [],
  },
  {
    id: '1003',
    name: 'Employee Training',
    type: 'folder',
    stage: 'draft',
    createdBy: 'Mike Chen',
    lastUpdated: 'Dec 15, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: null,
    children: [],
  },
  {
    id: '1004',
    name: 'Compliance & Administration',
    type: 'folder',
    stage: 'production',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Dec 12, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: null,
    children: [],
  },

  // Standalone root level items
  {
    id: '20001',
    name: 'Quick Reference Guide',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 14, 2025',
    lastUpdatedBy: 'Dr. Sarah Johnson',
    parentId: null,
    screenCount: 4,
    hasFlow: true,
  },
  {
    id: '20002',
    name: 'Emergency Contact Procedures',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Dec 13, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: null,
    screenCount: 3,
  },
  {
    id: '20003',
    name: 'New Employee Onboarding Guide',
    type: 'workflow',
    stage: 'draft',
    createdBy: 'Mike Chen',
    lastUpdated: 'Dec 15, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: null,
    screenCount: 6,
    hasFlow: true,
  },
  {
    id: '20004',
    name: 'Customer Service Training Simulation',
    type: 'simulation',
    stage: 'draft',
    createdBy: 'Mike Chen',
    lastUpdated: 'Dec 15, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: null,
    workflowCount: 3,
    hasAssessment: false,
    playgroundMode: true,
    selectedWorkflows: ['20001', '20002', '20003'],
  },
  {
    id: '20005',
    name: 'Product Demo Simulation',
    type: 'simulation',
    stage: 'draft',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 14, 2025',
    lastUpdatedBy: 'Dr. Sarah Johnson',
    parentId: null,
    workflowCount: 2,
    hasAssessment: true,
    playgroundMode: false,
    selectedWorkflows: ['20001', '20002'],
  },

  // ============================================
  // LEVEL 2: Folders inside Level 1
  // ============================================
  
  // Inside Clinical Services (1001)
  {
    id: '2001',
    name: 'Physical Therapy',
    type: 'folder',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 14, 2025',
    lastUpdatedBy: 'Dr. Sarah Johnson',
    parentId: '1001',
    children: [],
  },
  {
    id: '2002',
    name: 'Occupational Therapy',
    type: 'folder',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 14, 2025',
    lastUpdatedBy: 'Dr. Sarah Johnson',
    parentId: '1001',
    children: [],
  },
  {
    id: '2003',
    name: 'Speech-Language Pathology',
    type: 'folder',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 13, 2025',
    lastUpdatedBy: 'Dr. Sarah Johnson',
    parentId: '1001',
    children: [],
  },
  {
    id: '2004',
    name: 'Telehealth Services',
    type: 'folder',
    stage: 'draft',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 12, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '1001',
    children: [],
  },

  // Inside Patient Care Resources (1002)
  {
    id: '3001',
    name: 'Patient Onboarding',
    type: 'folder',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 13, 2025',
    lastUpdatedBy: 'Dr. Sarah Johnson',
    parentId: '1002',
    children: [],
  },
  {
    id: '3002',
    name: 'Home Care Programs',
    type: 'folder',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 12, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '1002',
    children: [],
  },
  {
    id: '3003',
    name: 'Patient Education',
    type: 'folder',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 11, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '1002',
    children: [],
  },

  // Inside Employee Training (1003)
  {
    id: '4001',
    name: 'New Employee Onboarding',
    type: 'folder',
    stage: 'production',
    createdBy: 'Mike Chen',
    lastUpdated: 'Dec 10, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '1003',
    children: [],
  },
  {
    id: '4002',
    name: 'Continuing Education',
    type: 'folder',
    stage: 'production',
    createdBy: 'Mike Chen',
    lastUpdated: 'Dec 9, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '1003',
    children: [],
  },
  {
    id: '4003',
    name: 'Clinical Workshops',
    type: 'folder',
    stage: 'draft',
    createdBy: 'Mike Chen',
    lastUpdated: 'Dec 8, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '1003',
    children: [],
  },

  // Inside Compliance & Administration (1004)
  {
    id: '5001',
    name: 'HIPAA Compliance',
    type: 'folder',
    stage: 'production',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Dec 7, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: '1004',
    children: [],
  },
  {
    id: '5002',
    name: 'Billing & Reimbursement',
    type: 'folder',
    stage: 'production',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Dec 6, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: '1004',
    children: [],
  },
  {
    id: '5003',
    name: 'Human Resources',
    type: 'folder',
    stage: 'draft',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Dec 5, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: '1004',
    children: [],
  },

  // ============================================
  // LEVEL 3: Items inside Level 2 folders
  // ============================================

  // Inside Physical Therapy (2001)
  {
    id: '6001',
    name: 'PT Assessment Forms',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 11, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '2001',
    screenCount: 8,
    hasFlow: true,
  },
  {
    id: '6002',
    name: 'Exercise Program Library',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 10, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '2001',
    screenCount: 6,
  },
  {
    id: '6003',
    name: 'PT Equipment Guidelines',
    type: 'workflow',
    stage: 'draft',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 9, 2025',
    lastUpdatedBy: 'Dr. Sarah Johnson',
    parentId: '2001',
    screenCount: 5,
  },
  {
    id: '6004',
    name: 'Orthopedic Treatment Protocols',
    type: 'simulation',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 8, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: null,
    workflowCount: 7,
    hasAssessment: true,
    playgroundMode: false,
    selectedWorkflows: ['6001', '6002', '6003'],
  },

  // Inside Occupational Therapy (2002)
  {
    id: '7001',
    name: 'OT Assessment Forms',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 7, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '2002',
    screenCount: 7,
    hasFlow: true,
  },
  {
    id: '7002',
    name: 'Daily Living Activities Guides',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 6, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '2002',
    screenCount: 6,
  },
  {
    id: '7003',
    name: 'Adaptive Equipment Manuals',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 5, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '2002',
    screenCount: 5,
  },
  {
    id: '7004',
    name: 'OT Intervention Strategies',
    type: 'simulation',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 4, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: null,
    workflowCount: 4,
    hasAssessment: true,
    playgroundMode: false,
    selectedWorkflows: ['7001', '7002'],
  },

  // Inside Speech-Language Pathology (2003)
  {
    id: '8001',
    name: 'SLP Evaluation Templates',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 3, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '2003',
    screenCount: 6,
  },
  {
    id: '8002',
    name: 'SLP Therapy Techniques',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 2, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '2003',
    screenCount: 7,
  },
  {
    id: '8003',
    name: 'Speech Assessment Tools',
    type: 'simulation',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Dec 1, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: null,
    workflowCount: 5,
    hasAssessment: true,
    playgroundMode: false,
    selectedWorkflows: ['8001', '8002'],
  },
  {
    id: '8004',
    name: 'Therapy Session Plans',
    type: 'workflow',
    stage: 'draft',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Nov 30, 2025',
    lastUpdatedBy: 'Dr. Sarah Johnson',
    parentId: '2003',
    screenCount: 5,
  },

  // Inside Telehealth Services (2004)
  {
    id: '9001',
    name: 'Telehealth Setup Guide',
    type: 'workflow',
    stage: 'draft',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Nov 29, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '2004',
    screenCount: 6,
  },
  {
    id: '9002',
    name: 'Remote Patient Assessment',
    type: 'workflow',
    stage: 'draft',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Nov 28, 2025',
    lastUpdatedBy: 'Dr. Sarah Johnson',
    parentId: '2004',
    screenCount: 5,
  },
  {
    id: '9003',
    name: 'Virtual Therapy Best Practices',
    type: 'simulation',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Nov 27, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: null,
    workflowCount: 4,
    hasAssessment: false,
    playgroundMode: false,
    selectedWorkflows: ['9001', '9002'],
  },

  // Inside Patient Onboarding (3001)
  {
    id: '10001',
    name: 'Initial Assessment Workflow',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Nov 26, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '3001',
    screenCount: 5,
    hasFlow: true,
  },
  {
    id: '10002',
    name: 'Patient Intake Forms',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Nov 25, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '3001',
    screenCount: 4,
  },
  {
    id: '10003',
    name: 'Welcome Orientation',
    type: 'simulation',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Nov 24, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: null,
    workflowCount: 3,
    hasAssessment: false,
    playgroundMode: false,
    selectedWorkflows: ['10001', '10002'],
  },

  // Inside Home Care Programs (3002)
  {
    id: '11001',
    name: 'Home Exercise Programs',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Nov 23, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '3002',
    screenCount: 6,
  },
  {
    id: '11002',
    name: 'Safety Assessment Checklist',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Nov 22, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '3002',
    screenCount: 5,
  },
  {
    id: '11003',
    name: 'Progress Tracking System',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Nov 21, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '3002',
    screenCount: 4,
  },

  // Inside Patient Education (3003)
  {
    id: '12001',
    name: 'Injury Prevention Guides',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Nov 20, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '3003',
    screenCount: 4,
  },
  {
    id: '12002',
    name: 'Recovery Timeline Expectations',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Nov 19, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '3003',
    screenCount: 5,
  },
  {
    id: '12003',
    name: 'Medication Management Guide',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Dr. Sarah Johnson',
    lastUpdated: 'Nov 18, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '3003',
    screenCount: 6,
  },

  // Inside New Employee Onboarding (4001)
  {
    id: '13001',
    name: 'Orientation Checklist',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Mike Chen',
    lastUpdated: 'Nov 17, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '4001',
    screenCount: 8,
    hasFlow: true,
  },
  {
    id: '13002',
    name: 'Company Policies Review',
    type: 'simulation',
    stage: 'production',
    createdBy: 'Mike Chen',
    lastUpdated: 'Nov 16, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: null,
    workflowCount: 6,
    hasAssessment: true,
    playgroundMode: false,
    selectedWorkflows: ['13001'],
  },
  {
    id: '13003',
    name: 'System Access Setup',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Mike Chen',
    lastUpdated: 'Nov 15, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '4001',
    screenCount: 5,
  },

  // Inside Continuing Education (4002)
  {
    id: '14001',
    name: 'CEU Course Catalog',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Mike Chen',
    lastUpdated: 'Nov 14, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '4002',
    screenCount: 5,
  },
  {
    id: '14002',
    name: 'CEU Credit Tracking',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Mike Chen',
    lastUpdated: 'Nov 13, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '4002',
    screenCount: 4,
  },
  {
    id: '14003',
    name: 'Webinar Recordings Library',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Mike Chen',
    lastUpdated: 'Nov 12, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '4002',
    screenCount: 3,
  },

  // Inside Clinical Workshops (4003)
  {
    id: '15001',
    name: 'Workshop Schedules',
    type: 'workflow',
    stage: 'draft',
    createdBy: 'Mike Chen',
    lastUpdated: 'Nov 11, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '4003',
    screenCount: 4,
  },
  {
    id: '15002',
    name: 'Workshop Materials',
    type: 'workflow',
    stage: 'draft',
    createdBy: 'Mike Chen',
    lastUpdated: 'Nov 10, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: '4003',
    screenCount: 5,
    hasFlow: true,
  },
  {
    id: '15003',
    name: 'Advanced Therapy Techniques',
    type: 'simulation',
    stage: 'production',
    createdBy: 'Mike Chen',
    lastUpdated: 'Nov 9, 2025',
    lastUpdatedBy: 'Mike Chen',
    parentId: null,
    workflowCount: 4,
    hasAssessment: true,
    playgroundMode: false,
    selectedWorkflows: ['15001', '15002'],
  },

  // Inside HIPAA Compliance (5001)
  {
    id: '16001',
    name: 'HIPAA Training Materials',
    type: 'simulation',
    stage: 'production',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Nov 8, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: null,
    workflowCount: 5,
    hasAssessment: true,
    playgroundMode: false,
    selectedWorkflows: ['16002', '16003'],
  },
  {
    id: '16002',
    name: 'Patient Privacy Protocols',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Nov 7, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: '5001',
    screenCount: 6,
  },
  {
    id: '16003',
    name: 'Data Security Guidelines',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Nov 6, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: '5001',
    screenCount: 5,
  },

  // Inside Billing & Reimbursement (5002)
  {
    id: '17001',
    name: 'Medicare Billing Procedures',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Nov 5, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: '5002',
    screenCount: 7,
  },
  {
    id: '17002',
    name: 'Insurance Verification',
    type: 'workflow',
    stage: 'production',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Nov 4, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: '5002',
    screenCount: 5,
  },
  {
    id: '17003',
    name: 'Claims Processing',
    type: 'workflow',
    stage: 'draft',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Nov 3, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: '5002',
    screenCount: 6,
  },

  // Inside Human Resources (5003)
  {
    id: '18001',
    name: 'Employee Handbook',
    type: 'workflow',
    stage: 'draft',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Nov 2, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: '5003',
    screenCount: 8,
  },
  {
    id: '18002',
    name: 'Benefits Overview',
    type: 'workflow',
    stage: 'draft',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Nov 1, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: '5003',
    screenCount: 4,
  },
  {
    id: '18003',
    name: 'State Licensure Requirements',
    type: 'workflow',
    stage: 'draft',
    createdBy: 'Emily Rodriguez',
    lastUpdated: 'Oct 31, 2025',
    lastUpdatedBy: 'Emily Rodriguez',
    parentId: '5003',
    screenCount: 5,
  },
];

